name: Monster Search site
 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
 
jobs:
  build:
    runs-on: ubunut-latest
 
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
     
    - name: Setup NodeJs
      uses: actions/setup-node@v2
      with:
        node-version: "v20.11.1"
 
    - name: Install dependencies
      run: npm install
 
    - name: Build app
      run: npm run build
 
    - name: Upload to S3
      uses: prajitrahul01/monster
      with:
        args: --acl public-read
        env:
          SOURCE_DIR: build/
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}